[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "aarch64-apple-ios",
  "aarch64-apple-ios-sim",
]
all-features = true

[advisories]
ignore = []
unmaintained = "workspace"

[licenses]
confidence-threshold = 0.8
unused-license-exception = "allow"
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]
exceptions = [
  { allow = ["MPL-2.0"], crate = "cssparser@0.36.0" },
  { allow = ["MPL-2.0"], crate = "cssparser-macros@0.6.1" },
  { allow = ["MPL-2.0"], crate = "dtoa-short@0.3.5" },
  { allow = ["MPL-2.0"], crate = "option-ext@0.2.0" },
  { allow = ["MPL-2.0"], crate = "selectors@0.36.1" },
  { allow = ["Apache-2.0 WITH LLVM-exception"], crate = "target-lexicon@0.12.16" },
  { allow = ["CDLA-Permissive-2.0"], crate = "webpki-roots@0.26.11" },
  { allow = ["CDLA-Permissive-2.0"], crate = "webpki-roots@1.0.7" },
]

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "simplest-path"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
